version: '3.9'
services:
  backend:
    container_name: app
    # build é o local onde foi criada a imagem.
    build: ./
    ports:
      - 3001:3001
    working_dir: /app
    volumes: 
      - ./src:/app/src
    platform: linux/x86_64
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] 
      #lista os processos sendo executados na porta 3001 caso exista algum
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      #realiza um ping no mysql para confirmar que ele esta operacional
      timeout: 10s
      retries: 5

